### ISSUE TITLE
Option for numbering

### ISSUE THREAD

**Issue by jkeirstead** [jkeirstead/jk-vita#2]
At the moment, you have to manually turn on numbering within each section by commenting out the `enumerate` environments.  It would be great if this was made as an option in the setup with an interface like:

```
\setnumbering[rev]{true}
```

**Comment by dlebauer** [comment]
Where is enumerate option set? 

I'd prefer a) not to have references numbered and b) to start with the most recent (as I hard-coded in my branch d109eaf25f92b763c642ee2c9f1622f2c9488e4a). Any suggestions for how to do this?

**Comment by jkeirstead** [comment]
The ordering of the publications is completely controlled by Biblatex.  You can change the preferences by tweaking the options on [this line](https://github.com/jkeirstead/jk-vita/blob/2aab5a56d724ded872852258f8662526b7294356/style/jk-vita.sty#L187) of the style file.  Here's a link for the [Biblatex manual](http://ctan.mirrorcatalogs.com/macros/latex/exptl/biblatex/doc/biblatex.pdf).

Note that this is for the publications only.  If you want to change the sorting of the YAML elements, you will need to do that for each section, e.g. [here](https://github.com/jkeirstead/jk-vita/blob/2aab5a56d724ded872852258f8662526b7294356/scripts/tex_functions.r#L10).  I will probably add a general "sorting" function in future to avoid the repetition, but a person might want different sorting for different sections so I didn't want to over-generalise.
