### ISSUE TITLE
License file?

### ISSUE THREAD

**Issue by dlebauer** [jkeirstead/jk-vita#4]
I've been looking for such an approach for a long time - thanks!

Do you have any restrictions on for re-use? I prefer to know explicitly before forking that it is okay to do so, and if I should give attribution.

**Comment by jkeirstead** [comment]
Completely forgot about that.  I've added an [MIT license](http://choosealicense.com/licenses/mit/) on the develop branch (it will be in the next release), so please go ahead and fork away!
